# Generated by Django 4.2.3 on 2023-07-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ittool', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plugin',
            options={'ordering': ['date_added', 'name'], 'verbose_name': 'Plugin', 'verbose_name_plural': 'Plugins'},
        ),
        migrations.AlterField(
            model_name='plugin',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date added'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='dev_name',
            field=models.CharField(max_length=255, verbose_name='Developer name'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='icon',
            field=models.ImageField(blank=True, upload_to='icons/%Y/%m/%d/', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
