# Generated by Django 4.2.3 on 2023-07-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ittool', '0002_alter_plugin_options_alter_plugin_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='description',
            field=models.TextField(default='With this plugin you can view images', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plugin',
            name='version',
            field=models.CharField(default='1.0.0', max_length=10, verbose_name='Version'),
            preserve_default=False,
        ),
    ]
