# Generated by Django 4.2.3 on 2023-08-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ittool', '0003_plugin_description_plugin_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItToolsVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('version', models.CharField(max_length=10, verbose_name='Version')),
                ('version_type', models.CharField(max_length=20, verbose_name='Version Type')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
            ],
            options={
                'verbose_name': 'ITTOOLS Version',
                'verbose_name_plural': 'ITTOOLS Versions',
                'ordering': ['version'],
            },
        ),
    ]
