# Generated by Django 4.2.3 on 2023-08-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ittool', '0004_ittoolsversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ittoolsversion',
            name='file',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d/', verbose_name='File'),
        ),
    ]
