# Generated by Django 4.2.3 on 2023-08-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ittool', '0005_ittoolsversion_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ittoolsversion',
            name='file',
            field=models.FileField(upload_to='files/%Y/%m/%d/', verbose_name='File'),
        ),
    ]
