# Generated by Django 4.2.3 on 2023-08-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ittool', '0007_alter_ittoolsversion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='description',
            field=models.TextField(max_length=180, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='dev_name',
            field=models.CharField(max_length=15, verbose_name='Developer name'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Name'),
        ),
    ]
